// import { init } from "../engine/gamelab_functions.js";

// const canvas = document.querySelector(".minimal");

const {
  getAll,    addTile,   onInput,   
  setScreenSize, setLegend, setMap,      sprite
} = require("./engine.js");

setScreenSize(500, 500*.8)

setLegend({
  p: sprite(`
................
................
................
................
.....000000.....
....00....00....
....0..0.0.0....
....00.....0....
.....0....0.....
.....000000.....
......0..00.....
.....00...0.....
.....0..........
................
................
................
  `),
})

setMap(`
...
.p.
...         
`)

addTile(4, 4, "p");
const log = x => (console.log(x), x);
let player = log(getAll("p")[0]);

onInput("up", _ => player.y -= 1)
onInput("down", _ => player.y += 1)
onInput("left", _ => player.x -= 1)
onInput("right", _ => player.x += 1)
