// import { init } from "../engine/gamelab_functions.js";

// const canvas = document.querySelector(".minimal");

const {
  addTile,       onInput,     sprite,
  setScreenSize, setLegend,   setMap,
  getTile,       getAllTiles,
} = require("./engine.js");

setScreenSize(500, 500*.8)

setLegend({
  p: sprite(`
................
................
................
................
.....000000.....
....00....00....
....0..0.0.0....
....00.....0....
.....0....0.....
.....000000.....
......0..00.....
.....00...0.....
.....0..........
................
................
................
  `),
})

setMap(`
...
.p.
...         
`)

let player = getTile("p");

onInput("up", _ => player.y -= 1)
onInput("down", _ => player.y += 1)
onInput("left", _ => player.x -= 1)
onInput("right", _ => player.x += 1)
